"""Initial schema

Revision ID: 8953be7146f0
Revises: 
Create Date: 2026-05-26 23:59:34.857239

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8953be7146f0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ProvisionZone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_name', sa.String(length=128), nullable=False),
    sa.Column('provision_img_host', sa.String(length=128), nullable=False),
    sa.Column('provision_mirror_host', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('zone_name')
    )
    op.create_table('ServerData',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_number', sa.Integer(), nullable=False),
    sa.Column('primary_ip', sa.String(length=15), nullable=False),
    sa.Column('primary_gw', sa.String(length=15), nullable=False),
    sa.Column('primary_nm', sa.String(length=15), nullable=False),
    sa.Column('primary_mac', sa.String(length=20), nullable=False),
    sa.Column('drac_ip', sa.String(length=15), nullable=True),
    sa.Column('drac_gw', sa.String(length=15), nullable=True),
    sa.Column('drac_nm', sa.String(length=15), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('dns_domain_name', sa.String(length=255), nullable=False),
    sa.Column('dns_server_primary', sa.String(length=15), nullable=False),
    sa.Column('dns_server_secondary', sa.String(length=15), nullable=True),
    sa.Column('dns_server_tertiary', sa.String(length=15), nullable=True),
    sa.Column('bootstrapped', sa.Boolean(), nullable=False),
    sa.Column('boot_os', sa.String(length=255), nullable=False),
    sa.Column('boot_os_version', sa.String(length=64), nullable=False),
    sa.Column('boot_profile', sa.String(length=128), nullable=False),
    sa.Column('boot_status', sa.String(length=128), nullable=False),
    sa.Column('operational_status', sa.String(length=255), nullable=False),
    sa.Column('ntp_server', sa.String(length=128), nullable=False),
    sa.Column('provision_zone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provision_zone_id'], ['ProvisionZone.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_number')
    )
    op.create_table('SwitchInfo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('switch_name', sa.String(length=255), nullable=False),
    sa.Column('switch_port', sa.String(length=255), nullable=False),
    sa.Column('server_number', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['server_number'], ['ServerData.server_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SwitchInfo')
    op.drop_table('ServerData')
    op.drop_table('ProvisionZone')
    # ### end Alembic commands ###
